export default {
  name: 'eventoProximo',
  title: 'Próximo Evento',
  type: 'document',
  fields: [
    { name: 'edicao', title: 'Edição', type: 'string', description: 'Ex: AlgoritmoHumano #7' },
    { name: 'tema', title: 'Tema', type: 'string', description: 'Deixar vazio se ainda não definido' },
    { name: 'data', title: 'Data', type: 'string', description: 'Ex: 3.ª feira - 7 de abril de 2026' },
    { name: 'dataISO', title: 'Data/Hora exacta (ISO)', type: 'datetime', description: 'Data e hora exactas do evento — usada para lembretes automáticos por email' },
    { name: 'horario', title: 'Horário', type: 'string', description: 'Ex: 18h30 – 20h30' },
    { name: 'local', title: 'Local', type: 'string', description: 'Ex: UPTEC Asprela' },
    { name: 'convidado', title: 'Convidado/a', type: 'string', description: 'Nome do/a convidado/a' },
    { name: 'convidadoLinkedIn', title: 'LinkedIn do/a Convidado/a', type: 'url' },
    { name: 'convidadoInstagram', title: 'Instagram do/a Convidado/a', type: 'string', description: 'Ex: @andreia.silva' },
    {
      name: 'imagemEvento',
      title: 'Imagem do Evento',
      type: 'image',
      options: { hotspot: true },
      description: 'Imagem de capa / banner principal do evento',
    },
    {
      name: 'fotosPostEvento',
      title: 'Fotos Pós-Evento',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
      description: 'Galeria de fotos carregadas após o evento',
    },
    {
      name: 'descricaoCurta',
      title: 'Descrição Curta',
      type: 'text',
      rows: 4,
      description: 'Texto introdutório do evento (aparece no topo do cartão)',
    },
    {
      name: 'descricaoLonga',
      title: 'Descrição da Sessão',
      type: 'text',
      rows: 6,
      description: 'Descrição detalhada do tema/sessão',
    },
    {
      name: 'maxParticipantes',
      title: 'Máx. Participantes',
      type: 'number',
      description: 'Limite de inscrições confirmadas',
    },
    {
      name: 'formularioAtivo',
      title: 'Inscrições Abertas',
      type: 'boolean',
      description: 'Ativar para abrir as inscrições. Desativar para fechar.',
      initialValue: false,
    },
  ],
}
